### ISSUE TITLE
Tratar erro API ASAAS

### ISSUE THREAD

**Issue by lordjack** [icarojobs/freezer-control#157]
Olá pessoal, ao utilizar o projeto como base para integração com a API ASAAS, me deparei com um problema para retornar algum erro de validação via API. Ao retornar um erro, ele vem nesse formato que não estou conseguindo pegar o erro e colocar em um Notification. Então crie uma função para percorrer o erro e retornar. Mas mesmo assim não vai, quando vou fazer o json_decoder ele retorna null. 

Alguém teria alguma dica de como tratar esse erro para conseguir colocar ele no Notification?

Problema encontrado segue abaixo:

```php

 $payment = self::Gateway()->payment()->create($chargeData);
 dd($payment);
// dd($this->checkStringJson($payment));

    function checkStringJson($data)
    {
        $jsonStartPos = strpos($data, '{');

        // Extrair o JSON da string original
        $jsonString = substr($data, $jsonStartPos);

        // Decodificar a string JSON para um objeto PHP
        $responseObj = json_decode($jsonString);

        // Verificar se a decodificação foi bem-sucedida
        if (json_last_error() === JSON_ERROR_NONE) {
            // Sucesso: Trabalhe com o objeto PHP
            return $responseObj;
        } else {
            // Falha: Informe o erro
            echo "Erro ao decodificar JSON: " . json_last_error_msg();
        }
    }
```
**Capturas de tela**\

![image](https://github.com/user-attachments/assets/1cee73e4-c2a8-44fd-aef2-617eb7a305bf)

Filament Version: 3.2.#\
PHP Version: 8.2.#\
Laravel Version: 10.10.#\
Database Driver:
- [ ] SQLite
- [x] MySQL
- [ ] PostgreSQL
- [ ] SQL Server

**Comment by esjdev** [comment]
```
function checkStringJson(array $data) {
        if (json_last_error() !== JSON_ERROR_NONE) {
            echo "Erro ao decodificar JSON: " . json_last_error_msg();
            return;
        }

        $jsonStartPos = substr($data["error"], strpos($data["error"], "{"));
        $responseObj = json_decode($jsonStartPos, true);
        echo $responseObj["errors"][0]["description"];
}

echo checkStringJson($payment);
```

**Comment by icarojobs** [comment]
> Olá pessoal, ao utilizar o projeto como base para integração com a API ASAAS, me deparei com um problema para retornar algum erro de validação via API. Ao retornar um erro, ele vem nesse formato que não estou conseguindo pegar o erro e colocar em um Notification. Então crie uma função para percorrer o erro e retornar. Mas mesmo assim não vai, quando vou fazer o json_decoder ele retorna null.
> 
> Alguém teria alguma dica de como tratar esse erro para conseguir colocar ele no Notification?
> 
> Problema encontrado segue abaixo:
> 
> ```
>  $payment = self::Gateway()->payment()->create($chargeData);
>  dd($payment);
> // dd($this->checkStringJson($payment));
> 
>     function checkStringJson($data)
>     {
>         $jsonStartPos = strpos($data, '{');
> 
>         // Extrair o JSON da string original
>         $jsonString = substr($data, $jsonStartPos);
> 
>         // Decodificar a string JSON para um objeto PHP
>         $responseObj = json_decode($jsonString);
> 
>         // Verificar se a decodificação foi bem-sucedida
>         if (json_last_error() === JSON_ERROR_NONE) {
>             // Sucesso: Trabalhe com o objeto PHP
>             return $responseObj;
>         } else {
>             // Falha: Informe o erro
>             echo "Erro ao decodificar JSON: " . json_last_error_msg();
>         }
>     }
> ```
> 
> **Capturas de tela**\
> 
> ![image](https://private-user-images.githubusercontent.com/6691621/352114058-1cee73e4-c2a8-44fd-aef2-617eb7a305bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MDQ5MjcsIm5iZiI6MTcyNDgwNDYyNywicGF0aCI6Ii82NjkxNjIxLzM1MjExNDA1OC0xY2VlNzNlNC1jMmE4LTQ0ZmQtYWVmMi02MTdlYjdhMzA1YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDAyMzQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTEwNDZiZWMzZmYxYTVmZmZlYTVlNDM5MTE5YzgwNGIyODlkYTdhZmNkMTBiMWQzYWQ4MjhkYjg5NWY1YzNmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aKwx9T50sy7h5I63eWXQgaqs1l8P2HgC6CHbAwhXzhs)
> 
> Filament Version: 3.2.# PHP Version: 8.2.# Laravel Version: 10.10.# Database Driver:
> 
> * [ ]  SQLite
> * [x]  MySQL
> * [ ]  PostgreSQL
> * [ ]  SQL Server

Resolvido ao vivo! Link da live: [https://www.youtube.com/live/CqaQylgmw4Q](https://www.youtube.com/live/CqaQylgmw4Q)
